Updates to interpreter and executor to support new executor
project-ivi/ivi pull request #137
Opened 2017-11-02 06:21 UTC by angushtlam

\#136

# Description

This PR updates the executor and interpreter to support the new executor rewrite.

# Change Log
Describe all changes made 

-`<FILE CHANGED>` : <Change> 
`src/interpreter/executor/interpret.js` - moved enums and the objects into respective files
`src/interpreter/executor/abstracts.js`- new file to reduce file size of executor
`src/interpreter/executor/enums.js` - new file to reduce file size of executor
`src/view/index.js` - updated the way console and variables get added to the state
`src/interpreter/executor/state.js` - updated the info that the state receives from the interpreter to save into the executor state
`src/view/console/index.js` - fixed console throwing a react error

# Manual Test Steps
Describe how a reviewer should test the changes. Include relevant workflows, API calls, etc...
**NOTE: All visual changes PR should include a screenshot**
The visualizer and console now works as intended

2017-11-03 01:50 UTC, zsmoore requested changes

2017-11-03 01:50 UTC, zsmoore commented on src/interpreter/executor/interpret.js
> +function acceptingConsole(buffer, currentState, currExpression, inputLine) {
I don't think this is necessary to add.
If we have a console log we will always consume it and only call this function once so we do not care about input state.

We can delete the line `currentState = stateEnum.CONSUMED` and just return consumed always in the return tuple

2017-11-03 01:50 UTC, zsmoore commented on src/interpreter/executor/interpret.js
> +            resTup = acceptingConsole(buffer, currentState, currExpression, inputLine);
See other comment.

2017-11-03 01:52 UTC, zsmoore commented
@angushtlam Do we want to update error output in this PR or handle it separately?

2017-11-04 05:39 UTC, zsmoore approved these changes
Pair programmed this with Angus.  Works perfectly. Great job!

2017-11-04 22:07 UTC, AlexPerri commented
Are the Travis checks failing a problem right now or is it just not updated for the new changes Zach made in the interpreter?

2017-11-05 01:26 UTC, AlexPerri approved these changes
👍

2017-11-06 00:53 UTC, noahpoz commented
I noticed that if there was a syntax error in the code, it seems to get locked in a execution state or something and I can't run any more code unless I refresh the page.

2017-11-06 00:58 UTC, zsmoore commented
@noahpoz I think this has to do with error code not actually getting output yet

2017-11-06 01:05 UTC, merged